package io.github.jiezhi.havebook.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import io.github.jiezhi.havebook.dao.DoubanBook;
import io.github.jiezhi.havebook.dao.MyBook;

import io.github.jiezhi.havebook.dao.DoubanBookDao;
import io.github.jiezhi.havebook.dao.MyBookDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig doubanBookDaoConfig;
    private final DaoConfig myBookDaoConfig;

    private final DoubanBookDao doubanBookDao;
    private final MyBookDao myBookDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        doubanBookDaoConfig = daoConfigMap.get(DoubanBookDao.class).clone();
        doubanBookDaoConfig.initIdentityScope(type);

        myBookDaoConfig = daoConfigMap.get(MyBookDao.class).clone();
        myBookDaoConfig.initIdentityScope(type);

        doubanBookDao = new DoubanBookDao(doubanBookDaoConfig, this);
        myBookDao = new MyBookDao(myBookDaoConfig, this);

        registerDao(DoubanBook.class, doubanBookDao);
        registerDao(MyBook.class, myBookDao);
    }
    
    public void clear() {
        doubanBookDaoConfig.getIdentityScope().clear();
        myBookDaoConfig.getIdentityScope().clear();
    }

    public DoubanBookDao getDoubanBookDao() {
        return doubanBookDao;
    }

    public MyBookDao getMyBookDao() {
        return myBookDao;
    }

}
