package io.github.jiezhi.havebook.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DOUBAN_BOOK".
 */
public class DoubanBook {

    private String alt;
    private String alt_title;
    private String authors;
    private String author_intro;
    private String binding;
    private String catalog;
    /** Not-null value. */
    private String id;
    private String image;
    private String img_large;
    private String img_medium;
    private String img_small;
    private String isbn10;
    private String isbn13;
    private String origin_title;
    private String pages;
    private String price;
    private String pubdate;
    private String publisher;
    private String ratingAverage;
    private String ratingMax;
    private String ratingMin;
    private Integer ratingNum;
    private String subtitle;
    private String summary;
    private String title;
    private String url;
    private String translator;
    private String tags;

    public DoubanBook() {
    }

    public DoubanBook(String alt, String alt_title, String authors, String author_intro, String binding, String catalog, String id, String image, String img_large, String img_medium, String img_small, String isbn10, String isbn13, String origin_title, String pages, String price, String pubdate, String publisher, String ratingAverage, String ratingMax, String ratingMin, Integer ratingNum, String subtitle, String summary, String title, String url, String translator, String tags) {
        this.alt = alt;
        this.alt_title = alt_title;
        this.authors = authors;
        this.author_intro = author_intro;
        this.binding = binding;
        this.catalog = catalog;
        this.id = id;
        this.image = image;
        this.img_large = img_large;
        this.img_medium = img_medium;
        this.img_small = img_small;
        this.isbn10 = isbn10;
        this.isbn13 = isbn13;
        this.origin_title = origin_title;
        this.pages = pages;
        this.price = price;
        this.pubdate = pubdate;
        this.publisher = publisher;
        this.ratingAverage = ratingAverage;
        this.ratingMax = ratingMax;
        this.ratingMin = ratingMin;
        this.ratingNum = ratingNum;
        this.subtitle = subtitle;
        this.summary = summary;
        this.title = title;
        this.url = url;
        this.translator = translator;
        this.tags = tags;
    }

    public String getAlt() {
        return alt;
    }

    public void setAlt(String alt) {
        this.alt = alt;
    }

    public String getAlt_title() {
        return alt_title;
    }

    public void setAlt_title(String alt_title) {
        this.alt_title = alt_title;
    }

    public String getAuthors() {
        return authors;
    }

    public void setAuthors(String authors) {
        this.authors = authors;
    }

    public String getAuthor_intro() {
        return author_intro;
    }

    public void setAuthor_intro(String author_intro) {
        this.author_intro = author_intro;
    }

    public String getBinding() {
        return binding;
    }

    public void setBinding(String binding) {
        this.binding = binding;
    }

    public String getCatalog() {
        return catalog;
    }

    public void setCatalog(String catalog) {
        this.catalog = catalog;
    }

    /** Not-null value. */
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(String id) {
        this.id = id;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getImg_large() {
        return img_large;
    }

    public void setImg_large(String img_large) {
        this.img_large = img_large;
    }

    public String getImg_medium() {
        return img_medium;
    }

    public void setImg_medium(String img_medium) {
        this.img_medium = img_medium;
    }

    public String getImg_small() {
        return img_small;
    }

    public void setImg_small(String img_small) {
        this.img_small = img_small;
    }

    public String getIsbn10() {
        return isbn10;
    }

    public void setIsbn10(String isbn10) {
        this.isbn10 = isbn10;
    }

    public String getIsbn13() {
        return isbn13;
    }

    public void setIsbn13(String isbn13) {
        this.isbn13 = isbn13;
    }

    public String getOrigin_title() {
        return origin_title;
    }

    public void setOrigin_title(String origin_title) {
        this.origin_title = origin_title;
    }

    public String getPages() {
        return pages;
    }

    public void setPages(String pages) {
        this.pages = pages;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getPubdate() {
        return pubdate;
    }

    public void setPubdate(String pubdate) {
        this.pubdate = pubdate;
    }

    public String getPublisher() {
        return publisher;
    }

    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    public String getRatingAverage() {
        return ratingAverage;
    }

    public void setRatingAverage(String ratingAverage) {
        this.ratingAverage = ratingAverage;
    }

    public String getRatingMax() {
        return ratingMax;
    }

    public void setRatingMax(String ratingMax) {
        this.ratingMax = ratingMax;
    }

    public String getRatingMin() {
        return ratingMin;
    }

    public void setRatingMin(String ratingMin) {
        this.ratingMin = ratingMin;
    }

    public Integer getRatingNum() {
        return ratingNum;
    }

    public void setRatingNum(Integer ratingNum) {
        this.ratingNum = ratingNum;
    }

    public String getSubtitle() {
        return subtitle;
    }

    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getTranslator() {
        return translator;
    }

    public void setTranslator(String translator) {
        this.translator = translator;
    }

    public String getTags() {
        return tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

}
