package io.github.jiezhi.havebook.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MY_BOOK".
 */
public class MyBook {

    private Long id;
    private String doubanId;
    private String isbn13;
    private String img_local;
    private java.util.Date collectDate;
    private java.util.Date modifyDate;
    private String title;
    private String myComment;
    private String myTag;
    private String myRating;
    private Integer pages;
    private Integer readingPages;
    private Boolean readFinish;
    private Boolean isLike;
    private Boolean isHave;
    private String whereFrom;

    public MyBook() {
    }

    public MyBook(Long id) {
        this.id = id;
    }

    public MyBook(Long id, String doubanId, String isbn13, String img_local, java.util.Date collectDate, java.util.Date modifyDate, String title, String myComment, String myTag, String myRating, Integer pages, Integer readingPages, Boolean readFinish, Boolean isLike, Boolean isHave, String whereFrom) {
        this.id = id;
        this.doubanId = doubanId;
        this.isbn13 = isbn13;
        this.img_local = img_local;
        this.collectDate = collectDate;
        this.modifyDate = modifyDate;
        this.title = title;
        this.myComment = myComment;
        this.myTag = myTag;
        this.myRating = myRating;
        this.pages = pages;
        this.readingPages = readingPages;
        this.readFinish = readFinish;
        this.isLike = isLike;
        this.isHave = isHave;
        this.whereFrom = whereFrom;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDoubanId() {
        return doubanId;
    }

    public void setDoubanId(String doubanId) {
        this.doubanId = doubanId;
    }

    public String getIsbn13() {
        return isbn13;
    }

    public void setIsbn13(String isbn13) {
        this.isbn13 = isbn13;
    }

    public String getImg_local() {
        return img_local;
    }

    public void setImg_local(String img_local) {
        this.img_local = img_local;
    }

    public java.util.Date getCollectDate() {
        return collectDate;
    }

    public void setCollectDate(java.util.Date collectDate) {
        this.collectDate = collectDate;
    }

    public java.util.Date getModifyDate() {
        return modifyDate;
    }

    public void setModifyDate(java.util.Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getMyComment() {
        return myComment;
    }

    public void setMyComment(String myComment) {
        this.myComment = myComment;
    }

    public String getMyTag() {
        return myTag;
    }

    public void setMyTag(String myTag) {
        this.myTag = myTag;
    }

    public String getMyRating() {
        return myRating;
    }

    public void setMyRating(String myRating) {
        this.myRating = myRating;
    }

    public Integer getPages() {
        return pages;
    }

    public void setPages(Integer pages) {
        this.pages = pages;
    }

    public Integer getReadingPages() {
        return readingPages;
    }

    public void setReadingPages(Integer readingPages) {
        this.readingPages = readingPages;
    }

    public Boolean getReadFinish() {
        return readFinish;
    }

    public void setReadFinish(Boolean readFinish) {
        this.readFinish = readFinish;
    }

    public Boolean getIsLike() {
        return isLike;
    }

    public void setIsLike(Boolean isLike) {
        this.isLike = isLike;
    }

    public Boolean getIsHave() {
        return isHave;
    }

    public void setIsHave(Boolean isHave) {
        this.isHave = isHave;
    }

    public String getWhereFrom() {
        return whereFrom;
    }

    public void setWhereFrom(String whereFrom) {
        this.whereFrom = whereFrom;
    }

}
